// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBBZ0RIWOqMH8bOkesp_n0yFV4LCQCMPI',
    appId: '1:63337842799:web:76643969092aa83b7ae59a',
    messagingSenderId: '63337842799',
    projectId: 'stroop-1987e',
    authDomain: 'stroop-1987e.firebaseapp.com',
    storageBucket: 'stroop-1987e.appspot.com',
    measurementId: 'G-NLVD4BMVVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwaNpW7B-XW8FSNrHC58apGG0IuqOqITk',
    appId: '1:63337842799:android:c86de25767a449597ae59a',
    messagingSenderId: '63337842799',
    projectId: 'stroop-1987e',
    storageBucket: 'stroop-1987e.appspot.com',
  );
}
